# -----------------------------------------------------------------------------
#  File:        analyzerlib.py
#  Description: Analyzer for ntuples created by TheNtupleMaker
#  Created:     Wed Jul  9 15:54:37 2014 by mkanalyzer.py
#  Author:      Halil Gamsizkan
# -----------------------------------------------------------------------------
import os, sys, re
from ROOT import *
from string import atof, atoi, split, strip, replace
from array import array
from math import *
from time import sleep
from sys import exit
# -----------------------------------------------------------------------------
gSystem.AddIncludePath("-Iinclude")
gROOT.ProcessLine(".L src/treestream.cc+")
gROOT.ProcessLine(".L src/pdg.cc+")
# -----------------------------------------------------------------------------
# -- Classes, procedures and functions
# -----------------------------------------------------------------------------
class outputFile:

	def __init__(self, filename, stream=None, savecount=50000):
		if stream != None:
			print "events will be skimmed to file", filename			
			self.tree = stream.tree().CloneTree(0)
			self.weight = Double()
			self.b_weight = self.tree.Branch("eventWeight", self.weight,
											 "eventWeight/D")
			self.SAVECOUNT = savecount
		else:
			self.tree = None
			self.b_weight = None

		self.entry = 0

		self.filename = filename
		self.file = TFile(filename, "recreate")

		self.hist = TH1F("counts", "", 1, 0, 1)
		self.hist.SetBit(TH1.kCanRebin)
		self.hist.SetStats(0)

		self.b_weight = 0

	def addEvent(self, weight=1.0):
		if self.tree == None: return

		self.file = self.tree.GetCurrentFile()
		self.file.cd()
		self.tree.Fill()

		self.entry += 1		
		if self.entry % self.SAVECOUNT == 0:
			self.tree.AutoSave("SaveSelf")

	def count(self, cond, w=1.0):
		self.hist.Fill(cond, w)

	def close(self):
		print "==> histograms saved to file", self.filename
		if self.tree != None:			
			print "==> events skimmed to file", self.filename
			self.file = self.tree.GetCurrentFile()

		self.file.cd()
		#self.file.Write("", TObject.kOverwrite)
		self.file.Write()
		self.file.ls()
		self.file.Close()
# -----------------------------------------------------------------------------
class commandLine:
	def __init__(self):
		pass

def decodeCommandLine():
	argv = sys.argv
	argc = len(argv)

	cl = commandLine()
	cl.progname = split(os.path.basename(argv[0]),'.')[0]

	if argc > 1:
		cl.filelist = argv[1]
	else:
		cl.filelist = "filelist.txt"

	if argc > 2: 
		cl.outputfilename = argv[2] # 2nd (optional) command line argument
	else:
		cl.outputfilename = cl.progname + "_histograms"

	# Make sure extension is ".root"
	if cl.outputfilename[:-5] != ".root": cl.outputfilename += ".root"
	print "==> output to:", cl.outputfilename

	return cl
# -----------------------------------------------------------------------------
def error(message):
	print "** error ** " + message
	sys.exit(0)
# -----------------------------------------------------------------------------
#  Read ntuple filenames from file list

def getFilenames(filelist):
	if not os.path.exists(filelist):
		error("unable to open file: " + filelist)

	# Get ntuple file names
	filenames = filter(lambda x: x != "",
					   map(strip, open(filelist).readlines()))
	v = vector("string")()
	for filename in filenames: v.push_back(filename)
	return v
# -----------------------------------------------------------------------------
TEXTFONT = 42
TEXTSIZE = 0.031
#------------------------------------------------------------------------------
def setStyle():
	gROOT.SetStyle("Pub")
	style = gROOT.GetStyle("Pub")
	style.SetPalette(1)

	# For the canvas
	style.SetCanvasBorderMode(0)
	style.SetCanvasColor(kWhite)
	style.SetCanvasDefH(500)
	style.SetCanvasDefW(500)
	style.SetCanvasDefX(0)
	style.SetCanvasDefY(0)

	# For the pad
	style.SetPadBorderMode(0)
	style.SetPadColor(kWhite)
	style.SetPadGridX(kFALSE)
	style.SetPadGridY(kTRUE)
	style.SetGridColor(kGreen)
	style.SetGridStyle(3)
	style.SetGridWidth(1)

	# For the frame
	style.SetFrameBorderMode(0)
	style.SetFrameBorderSize(1)
	style.SetFrameFillColor(0)
	style.SetFrameFillStyle(0)
	style.SetFrameLineColor(1)
	style.SetFrameLineStyle(1)
	style.SetFrameLineWidth(1)

	# For the histogram
	style.SetHistLineColor(1)
	style.SetHistLineStyle(0)
	style.SetHistLineWidth(1)
	style.SetEndErrorSize(2)
	#style.SetErrorX(0.)
	style.SetMarkerSize(0.1)
	style.SetMarkerStyle(20)

	# For the fit/function
	style.SetOptFit(1)
	style.SetFitFormat("5.4g")
	style.SetFuncColor(2)
	style.SetFuncStyle(1)
	style.SetFuncWidth(1)

	#For the date
	style.SetOptDate(0)

	# For the statistics box
	style.SetOptFile(0)
	style.SetOptStat("")
	# To display the mean and RMS
	#style.SetOptStat("mr") 
	style.SetStatColor(kWhite)
	style.SetStatFont(TEXTFONT)
	style.SetStatFontSize(TEXTSIZE)
	style.SetStatTextColor(1)
	style.SetStatFormat("6.4g")
	style.SetStatBorderSize(1)
	style.SetStatH(0.2)
	style.SetStatW(0.3)

	# Margins
	style.SetPadTopMargin(0.05)
	style.SetPadBottomMargin(0.16)
	style.SetPadLeftMargin(0.16)
	style.SetPadRightMargin(0.16)

	# For the global title
	style.SetOptTitle(0)
	style.SetTitleFont(TEXTFONT)
	style.SetTitleColor(1)
	style.SetTitleTextColor(1)
	style.SetTitleFillColor(10)
	style.SetTitleFontSize(TEXTSIZE*1.1)

	# For the axis titles
	style.SetTitleColor(1, "XYZ")
	style.SetTitleFont(TEXTFONT, "XYZ")
	style.SetTitleSize(TEXTSIZE*1.2, "XYZ") # 0,05
	style.SetTitleXOffset(1.25) # 0.9
	style.SetTitleYOffset(1.25) # 1.25

	# For the axis labels
	style.SetLabelColor(1, "XYZ")
	style.SetLabelFont(TEXTFONT, "XYZ")
	style.SetLabelOffset(0.006, "XYZ")
	style.SetLabelSize(TEXTSIZE*1.2, "XYZ")

	# For the axis
	style.SetAxisColor(1, "XYZ")
	style.SetStripDecimals(kTRUE)
	style.SetTickLength(0.03, "XYZ")
	style.SetNdivisions(505, "XYZ")

	# To get tick marks on the opposite side of the frame
	style.SetPadTickX(1)  
	style.SetPadTickY(1)

	# Change for log plots
	style.SetOptLogx(0)
	style.SetOptLogy(0)
	style.SetOptLogz(0)

	# Postscript options
	style.SetPaperSize(20.,20.)

	style.cd()
# -----------------------------------------------------------------------------
#  Define variables to be read
# -----------------------------------------------------------------------------
GenJet_auxiliaryEnergy	= vector("float")(200)
GenJet_charge	= vector("int")(200)
GenJet_constituentEtaPhiSpread	= vector("float")(200)
GenJet_constituentPtDistribution	= vector("float")(200)
GenJet_emEnergy	= vector("float")(200)
GenJet_energy	= vector("double")(200)
GenJet_et	= vector("double")(200)
GenJet_eta	= vector("double")(200)
GenJet_etaetaMoment	= vector("float")(200)
GenJet_etaphiMoment	= vector("float")(200)
GenJet_hadEnergy	= vector("float")(200)
GenJet_hasMasterClone	= vector("int")(200)
GenJet_hasMasterClonePtr	= vector("int")(200)
GenJet_invisibleEnergy	= vector("float")(200)
GenJet_isCaloMuon	= vector("int")(200)
GenJet_isConvertedPhoton	= vector("int")(200)
GenJet_isElectron	= vector("int")(200)
GenJet_isGlobalMuon	= vector("int")(200)
GenJet_isJet	= vector("int")(200)
GenJet_isMuon	= vector("int")(200)
GenJet_isPhoton	= vector("int")(200)
GenJet_isStandAloneMuon	= vector("int")(200)
GenJet_isTrackerMuon	= vector("int")(200)
GenJet_jetArea	= vector("float")(200)
GenJet_longLived	= vector("int")(200)
GenJet_mass	= vector("double")(200)
GenJet_massConstraint	= vector("int")(200)
GenJet_massSqr	= vector("double")(200)
GenJet_maxDistance	= vector("float")(200)
GenJet_mt	= vector("double")(200)
GenJet_mtSqr	= vector("double")(200)
GenJet_nConstituents	= vector("int")(200)
GenJet_nPasses	= vector("int")(200)
GenJet_numberOfDaughters	= vector("size_t")(200)
GenJet_numberOfMothers	= vector("size_t")(200)
GenJet_numberOfSourceCandidatePtrs	= vector("size_t")(200)
GenJet_p	= vector("double")(200)
GenJet_pdgId	= vector("int")(200)
GenJet_phi	= vector("double")(200)
GenJet_phiphiMoment	= vector("float")(200)
GenJet_pileup	= vector("float")(200)
GenJet_pt	= vector("double")(200)
GenJet_px	= vector("double")(200)
GenJet_py	= vector("double")(200)
GenJet_pz	= vector("double")(200)
GenJet_rapidity	= vector("double")(200)
GenJet_status	= vector("int")(200)
GenJet_theta	= vector("double")(200)
GenJet_threeCharge	= vector("int")(200)
GenJet_vertexChi2	= vector("double")(200)
GenJet_vertexNdof	= vector("double")(200)
GenJet_vertexNormalizedChi2	= vector("double")(200)
GenJet_vx	= vector("double")(200)
GenJet_vy	= vector("double")(200)
GenJet_vz	= vector("double")(200)
GenJet_y	= vector("double")(200)
GenMET_ChargedEMEt	= vector("double")(200)
GenMET_ChargedEMEtFraction	= vector("double")(200)
GenMET_ChargedHadEt	= vector("double")(200)
GenMET_ChargedHadEtFraction	= vector("double")(200)
GenMET_InvisibleEt	= vector("double")(200)
GenMET_InvisibleEtFraction	= vector("double")(200)
GenMET_MuonEt	= vector("double")(200)
GenMET_MuonEtFraction	= vector("double")(200)
GenMET_NeutralEMEt	= vector("double")(200)
GenMET_NeutralEMEtFraction	= vector("double")(200)
GenMET_NeutralHadEt	= vector("double")(200)
GenMET_NeutralHadEtFraction	= vector("double")(200)
GenMET_auxiliaryEnergy	= vector("double")(200)
GenMET_charge	= vector("int")(200)
GenMET_e_longitudinal	= vector("double")(200)
GenMET_emEnergy	= vector("double")(200)
GenMET_energy	= vector("double")(200)
GenMET_et	= vector("double")(200)
GenMET_eta	= vector("double")(200)
GenMET_hadEnergy	= vector("double")(200)
GenMET_hasMasterClone	= vector("int")(200)
GenMET_hasMasterClonePtr	= vector("int")(200)
GenMET_invisibleEnergy	= vector("double")(200)
GenMET_isCaloMuon	= vector("int")(200)
GenMET_isConvertedPhoton	= vector("int")(200)
GenMET_isElectron	= vector("int")(200)
GenMET_isGlobalMuon	= vector("int")(200)
GenMET_isJet	= vector("int")(200)
GenMET_isMuon	= vector("int")(200)
GenMET_isPhoton	= vector("int")(200)
GenMET_isStandAloneMuon	= vector("int")(200)
GenMET_isTrackerMuon	= vector("int")(200)
GenMET_longLived	= vector("int")(200)
GenMET_mEtSig	= vector("double")(200)
GenMET_mass	= vector("double")(200)
GenMET_massConstraint	= vector("int")(200)
GenMET_massSqr	= vector("double")(200)
GenMET_mt	= vector("double")(200)
GenMET_mtSqr	= vector("double")(200)
GenMET_numberOfDaughters	= vector("size_t")(200)
GenMET_numberOfMothers	= vector("size_t")(200)
GenMET_numberOfSourceCandidatePtrs	= vector("size_t")(200)
GenMET_numberOfTracks	= vector("size_t")(200)
GenMET_p	= vector("double")(200)
GenMET_pdgId	= vector("int")(200)
GenMET_phi	= vector("double")(200)
GenMET_pt	= vector("double")(200)
GenMET_px	= vector("double")(200)
GenMET_py	= vector("double")(200)
GenMET_pz	= vector("double")(200)
GenMET_rapidity	= vector("double")(200)
GenMET_significance	= vector("double")(200)
GenMET_status	= vector("int")(200)
GenMET_sumEt	= vector("double")(200)
GenMET_theta	= vector("double")(200)
GenMET_threeCharge	= vector("int")(200)
GenMET_vertexChi2	= vector("double")(200)
GenMET_vertexNdof	= vector("double")(200)
GenMET_vertexNormalizedChi2	= vector("double")(200)
GenMET_vx	= vector("double")(200)
GenMET_vy	= vector("double")(200)
GenMET_vz	= vector("double")(200)
GenMET_y	= vector("double")(200)
GenParticle_charge	= vector("int")(200)
GenParticle_collisionId	= vector("int")(200)
GenParticle_energy	= vector("double")(200)
GenParticle_et	= vector("double")(200)
GenParticle_eta	= vector("double")(200)
GenParticle_hasMasterClone	= vector("int")(200)
GenParticle_hasMasterClonePtr	= vector("int")(200)
GenParticle_isCaloMuon	= vector("int")(200)
GenParticle_isConvertedPhoton	= vector("int")(200)
GenParticle_isElectron	= vector("int")(200)
GenParticle_isGlobalMuon	= vector("int")(200)
GenParticle_isJet	= vector("int")(200)
GenParticle_isMuon	= vector("int")(200)
GenParticle_isPhoton	= vector("int")(200)
GenParticle_isStandAloneMuon	= vector("int")(200)
GenParticle_isTrackerMuon	= vector("int")(200)
GenParticle_longLived	= vector("int")(200)
GenParticle_mass	= vector("double")(200)
GenParticle_massConstraint	= vector("int")(200)
GenParticle_massSqr	= vector("double")(200)
GenParticle_mt	= vector("double")(200)
GenParticle_mtSqr	= vector("double")(200)
GenParticle_numberOfDaughters	= vector("size_t")(200)
GenParticle_numberOfMothers	= vector("size_t")(200)
GenParticle_numberOfSourceCandidatePtrs	= vector("size_t")(200)
GenParticle_p	= vector("double")(200)
GenParticle_pdgId	= vector("int")(200)
GenParticle_phi	= vector("double")(200)
GenParticle_pt	= vector("double")(200)
GenParticle_px	= vector("double")(200)
GenParticle_py	= vector("double")(200)
GenParticle_pz	= vector("double")(200)
GenParticle_rapidity	= vector("double")(200)
GenParticle_status	= vector("int")(200)
GenParticle_theta	= vector("double")(200)
GenParticle_threeCharge	= vector("int")(200)
GenParticle_vertexChi2	= vector("double")(200)
GenParticle_vertexNdof	= vector("double")(200)
GenParticle_vertexNormalizedChi2	= vector("double")(200)
GenParticle_vx	= vector("double")(200)
GenParticle_vy	= vector("double")(200)
GenParticle_vz	= vector("double")(200)
GenParticle_y	= vector("double")(200)
PFJet_HFEMEnergy	= vector("float")(200)
PFJet_HFEMEnergyFraction	= vector("float")(200)
PFJet_HFEMMultiplicity	= vector("int")(200)
PFJet_HFHadronEnergy	= vector("float")(200)
PFJet_HFHadronEnergyFraction	= vector("float")(200)
PFJet_HFHadronMultiplicity	= vector("int")(200)
PFJet_charge	= vector("int")(200)
PFJet_chargedEmEnergy	= vector("float")(200)
PFJet_chargedEmEnergyFraction	= vector("float")(200)
PFJet_chargedHadronEnergy	= vector("float")(200)
PFJet_chargedHadronEnergyFraction	= vector("float")(200)
PFJet_chargedHadronMultiplicity	= vector("int")(200)
PFJet_chargedMuEnergy	= vector("float")(200)
PFJet_chargedMuEnergyFraction	= vector("float")(200)
PFJet_chargedMultiplicity	= vector("int")(200)
PFJet_constituentEtaPhiSpread	= vector("float")(200)
PFJet_constituentPtDistribution	= vector("float")(200)
PFJet_electronEnergy	= vector("float")(200)
PFJet_electronEnergyFraction	= vector("float")(200)
PFJet_electronMultiplicity	= vector("int")(200)
PFJet_energy	= vector("double")(200)
PFJet_et	= vector("double")(200)
PFJet_eta	= vector("double")(200)
PFJet_etaetaMoment	= vector("float")(200)
PFJet_etaphiMoment	= vector("float")(200)
PFJet_hasMasterClone	= vector("int")(200)
PFJet_hasMasterClonePtr	= vector("int")(200)
PFJet_isCaloMuon	= vector("int")(200)
PFJet_isConvertedPhoton	= vector("int")(200)
PFJet_isElectron	= vector("int")(200)
PFJet_isGlobalMuon	= vector("int")(200)
PFJet_isJet	= vector("int")(200)
PFJet_isMuon	= vector("int")(200)
PFJet_isPhoton	= vector("int")(200)
PFJet_isStandAloneMuon	= vector("int")(200)
PFJet_isTrackerMuon	= vector("int")(200)
PFJet_jetArea	= vector("float")(200)
PFJet_longLived	= vector("int")(200)
PFJet_mass	= vector("double")(200)
PFJet_massConstraint	= vector("int")(200)
PFJet_massSqr	= vector("double")(200)
PFJet_maxDistance	= vector("float")(200)
PFJet_mt	= vector("double")(200)
PFJet_mtSqr	= vector("double")(200)
PFJet_muonEnergy	= vector("float")(200)
PFJet_muonEnergyFraction	= vector("float")(200)
PFJet_muonMultiplicity	= vector("int")(200)
PFJet_nConstituents	= vector("int")(200)
PFJet_nPasses	= vector("int")(200)
PFJet_neutralEmEnergy	= vector("float")(200)
PFJet_neutralEmEnergyFraction	= vector("float")(200)
PFJet_neutralHadronEnergy	= vector("float")(200)
PFJet_neutralHadronEnergyFraction	= vector("float")(200)
PFJet_neutralHadronMultiplicity	= vector("int")(200)
PFJet_neutralMultiplicity	= vector("int")(200)
PFJet_numberOfDaughters	= vector("size_t")(200)
PFJet_numberOfMothers	= vector("size_t")(200)
PFJet_numberOfSourceCandidatePtrs	= vector("size_t")(200)
PFJet_p	= vector("double")(200)
PFJet_pdgId	= vector("int")(200)
PFJet_phi	= vector("double")(200)
PFJet_phiphiMoment	= vector("float")(200)
PFJet_photonEnergy	= vector("float")(200)
PFJet_photonEnergyFraction	= vector("float")(200)
PFJet_photonMultiplicity	= vector("int")(200)
PFJet_pileup	= vector("float")(200)
PFJet_pt	= vector("double")(200)
PFJet_px	= vector("double")(200)
PFJet_py	= vector("double")(200)
PFJet_pz	= vector("double")(200)
PFJet_rapidity	= vector("double")(200)
PFJet_status	= vector("int")(200)
PFJet_theta	= vector("double")(200)
PFJet_threeCharge	= vector("int")(200)
PFJet_vertexChi2	= vector("double")(200)
PFJet_vertexNdof	= vector("double")(200)
PFJet_vertexNormalizedChi2	= vector("double")(200)
PFJet_vx	= vector("double")(200)
PFJet_vy	= vector("double")(200)
PFJet_vz	= vector("double")(200)
PFJet_y	= vector("double")(200)
PFMET_ChargedEMEt	= vector("double")(200)
PFMET_ChargedEMEtFraction	= vector("double")(200)
PFMET_ChargedEMFraction	= vector("double")(200)
PFMET_ChargedHadEt	= vector("double")(200)
PFMET_ChargedHadEtFraction	= vector("double")(200)
PFMET_ChargedHadFraction	= vector("double")(200)
PFMET_HFEMEt	= vector("double")(200)
PFMET_HFEMEtFraction	= vector("double")(200)
PFMET_HFHadronEt	= vector("double")(200)
PFMET_HFHadronEtFraction	= vector("double")(200)
PFMET_MuonEt	= vector("double")(200)
PFMET_MuonEtFraction	= vector("double")(200)
PFMET_MuonFraction	= vector("double")(200)
PFMET_NeutralEMEt	= vector("double")(200)
PFMET_NeutralEMEtFraction	= vector("double")(200)
PFMET_NeutralEMFraction	= vector("double")(200)
PFMET_NeutralHadEt	= vector("double")(200)
PFMET_NeutralHadEtFraction	= vector("double")(200)
PFMET_NeutralHadFraction	= vector("double")(200)
PFMET_Type6Et	= vector("double")(200)
PFMET_Type6EtFraction	= vector("double")(200)
PFMET_Type7Et	= vector("double")(200)
PFMET_Type7EtFraction	= vector("double")(200)
PFMET_charge	= vector("int")(200)
PFMET_chargedHadronEt	= vector("double")(200)
PFMET_chargedHadronEtFraction	= vector("double")(200)
PFMET_e_longitudinal	= vector("double")(200)
PFMET_electronEt	= vector("double")(200)
PFMET_electronEtFraction	= vector("double")(200)
PFMET_energy	= vector("double")(200)
PFMET_et	= vector("double")(200)
PFMET_eta	= vector("double")(200)
PFMET_hasMasterClone	= vector("int")(200)
PFMET_hasMasterClonePtr	= vector("int")(200)
PFMET_isCaloMuon	= vector("int")(200)
PFMET_isConvertedPhoton	= vector("int")(200)
PFMET_isElectron	= vector("int")(200)
PFMET_isGlobalMuon	= vector("int")(200)
PFMET_isJet	= vector("int")(200)
PFMET_isMuon	= vector("int")(200)
PFMET_isPhoton	= vector("int")(200)
PFMET_isStandAloneMuon	= vector("int")(200)
PFMET_isTrackerMuon	= vector("int")(200)
PFMET_longLived	= vector("int")(200)
PFMET_mEtSig	= vector("double")(200)
PFMET_mass	= vector("double")(200)
PFMET_massConstraint	= vector("int")(200)
PFMET_massSqr	= vector("double")(200)
PFMET_mt	= vector("double")(200)
PFMET_mtSqr	= vector("double")(200)
PFMET_muonEt	= vector("double")(200)
PFMET_muonEtFraction	= vector("double")(200)
PFMET_neutralHadronEt	= vector("double")(200)
PFMET_neutralHadronEtFraction	= vector("double")(200)
PFMET_numberOfDaughters	= vector("size_t")(200)
PFMET_numberOfMothers	= vector("size_t")(200)
PFMET_numberOfSourceCandidatePtrs	= vector("size_t")(200)
PFMET_numberOfTracks	= vector("size_t")(200)
PFMET_p	= vector("double")(200)
PFMET_pdgId	= vector("int")(200)
PFMET_phi	= vector("double")(200)
PFMET_photonEt	= vector("double")(200)
PFMET_photonEtFraction	= vector("double")(200)
PFMET_pt	= vector("double")(200)
PFMET_px	= vector("double")(200)
PFMET_py	= vector("double")(200)
PFMET_pz	= vector("double")(200)
PFMET_rapidity	= vector("double")(200)
PFMET_significance	= vector("double")(200)
PFMET_status	= vector("int")(200)
PFMET_sumEt	= vector("double")(200)
PFMET_theta	= vector("double")(200)
PFMET_threeCharge	= vector("int")(200)
PFMET_vertexChi2	= vector("double")(200)
PFMET_vertexNdof	= vector("double")(200)
PFMET_vertexNormalizedChi2	= vector("double")(200)
PFMET_vx	= vector("double")(200)
PFMET_vy	= vector("double")(200)
PFMET_vz	= vector("double")(200)
PFMET_y	= vector("double")(200)
TriggerResults_accept	= Long()
TriggerResults_error	= Long()
TriggerResults_wasrun	= Long()
nGenJet	= Long()
nGenMET	= Long()
nGenParticle	= Long()
nPFJet	= Long()
nPFMET	= Long()
nTriggerResults	= Long()

stream.select("recoGenJet_ak5GenJets.auxiliaryEnergy", GenJet_auxiliaryEnergy)
stream.select("recoGenJet_ak5GenJets.charge", GenJet_charge)
stream.select("recoGenJet_ak5GenJets.constituentEtaPhiSpread", GenJet_constituentEtaPhiSpread)
stream.select("recoGenJet_ak5GenJets.constituentPtDistribution", GenJet_constituentPtDistribution)
stream.select("recoGenJet_ak5GenJets.emEnergy", GenJet_emEnergy)
stream.select("recoGenJet_ak5GenJets.energy", GenJet_energy)
stream.select("recoGenJet_ak5GenJets.et", GenJet_et)
stream.select("recoGenJet_ak5GenJets.eta", GenJet_eta)
stream.select("recoGenJet_ak5GenJets.etaetaMoment", GenJet_etaetaMoment)
stream.select("recoGenJet_ak5GenJets.etaphiMoment", GenJet_etaphiMoment)
stream.select("recoGenJet_ak5GenJets.hadEnergy", GenJet_hadEnergy)
stream.select("recoGenJet_ak5GenJets.hasMasterClone", GenJet_hasMasterClone)
stream.select("recoGenJet_ak5GenJets.hasMasterClonePtr", GenJet_hasMasterClonePtr)
stream.select("recoGenJet_ak5GenJets.invisibleEnergy", GenJet_invisibleEnergy)
stream.select("recoGenJet_ak5GenJets.isCaloMuon", GenJet_isCaloMuon)
stream.select("recoGenJet_ak5GenJets.isConvertedPhoton", GenJet_isConvertedPhoton)
stream.select("recoGenJet_ak5GenJets.isElectron", GenJet_isElectron)
stream.select("recoGenJet_ak5GenJets.isGlobalMuon", GenJet_isGlobalMuon)
stream.select("recoGenJet_ak5GenJets.isJet", GenJet_isJet)
stream.select("recoGenJet_ak5GenJets.isMuon", GenJet_isMuon)
stream.select("recoGenJet_ak5GenJets.isPhoton", GenJet_isPhoton)
stream.select("recoGenJet_ak5GenJets.isStandAloneMuon", GenJet_isStandAloneMuon)
stream.select("recoGenJet_ak5GenJets.isTrackerMuon", GenJet_isTrackerMuon)
stream.select("recoGenJet_ak5GenJets.jetArea", GenJet_jetArea)
stream.select("recoGenJet_ak5GenJets.longLived", GenJet_longLived)
stream.select("recoGenJet_ak5GenJets.mass", GenJet_mass)
stream.select("recoGenJet_ak5GenJets.massConstraint", GenJet_massConstraint)
stream.select("recoGenJet_ak5GenJets.massSqr", GenJet_massSqr)
stream.select("recoGenJet_ak5GenJets.maxDistance", GenJet_maxDistance)
stream.select("recoGenJet_ak5GenJets.mt", GenJet_mt)
stream.select("recoGenJet_ak5GenJets.mtSqr", GenJet_mtSqr)
stream.select("recoGenJet_ak5GenJets.nConstituents", GenJet_nConstituents)
stream.select("recoGenJet_ak5GenJets.nPasses", GenJet_nPasses)
stream.select("recoGenJet_ak5GenJets.numberOfDaughters", GenJet_numberOfDaughters)
stream.select("recoGenJet_ak5GenJets.numberOfMothers", GenJet_numberOfMothers)
stream.select("recoGenJet_ak5GenJets.numberOfSourceCandidatePtrs", GenJet_numberOfSourceCandidatePtrs)
stream.select("recoGenJet_ak5GenJets.p", GenJet_p)
stream.select("recoGenJet_ak5GenJets.pdgId", GenJet_pdgId)
stream.select("recoGenJet_ak5GenJets.phi", GenJet_phi)
stream.select("recoGenJet_ak5GenJets.phiphiMoment", GenJet_phiphiMoment)
stream.select("recoGenJet_ak5GenJets.pileup", GenJet_pileup)
stream.select("recoGenJet_ak5GenJets.pt", GenJet_pt)
stream.select("recoGenJet_ak5GenJets.px", GenJet_px)
stream.select("recoGenJet_ak5GenJets.py", GenJet_py)
stream.select("recoGenJet_ak5GenJets.pz", GenJet_pz)
stream.select("recoGenJet_ak5GenJets.rapidity", GenJet_rapidity)
stream.select("recoGenJet_ak5GenJets.status", GenJet_status)
stream.select("recoGenJet_ak5GenJets.theta", GenJet_theta)
stream.select("recoGenJet_ak5GenJets.threeCharge", GenJet_threeCharge)
stream.select("recoGenJet_ak5GenJets.vertexChi2", GenJet_vertexChi2)
stream.select("recoGenJet_ak5GenJets.vertexNdof", GenJet_vertexNdof)
stream.select("recoGenJet_ak5GenJets.vertexNormalizedChi2", GenJet_vertexNormalizedChi2)
stream.select("recoGenJet_ak5GenJets.vx", GenJet_vx)
stream.select("recoGenJet_ak5GenJets.vy", GenJet_vy)
stream.select("recoGenJet_ak5GenJets.vz", GenJet_vz)
stream.select("recoGenJet_ak5GenJets.y", GenJet_y)
stream.select("recoGenMET_genMetCalo.ChargedEMEt", GenMET_ChargedEMEt)
stream.select("recoGenMET_genMetCalo.ChargedEMEtFraction", GenMET_ChargedEMEtFraction)
stream.select("recoGenMET_genMetCalo.ChargedHadEt", GenMET_ChargedHadEt)
stream.select("recoGenMET_genMetCalo.ChargedHadEtFraction", GenMET_ChargedHadEtFraction)
stream.select("recoGenMET_genMetCalo.InvisibleEt", GenMET_InvisibleEt)
stream.select("recoGenMET_genMetCalo.InvisibleEtFraction", GenMET_InvisibleEtFraction)
stream.select("recoGenMET_genMetCalo.MuonEt", GenMET_MuonEt)
stream.select("recoGenMET_genMetCalo.MuonEtFraction", GenMET_MuonEtFraction)
stream.select("recoGenMET_genMetCalo.NeutralEMEt", GenMET_NeutralEMEt)
stream.select("recoGenMET_genMetCalo.NeutralEMEtFraction", GenMET_NeutralEMEtFraction)
stream.select("recoGenMET_genMetCalo.NeutralHadEt", GenMET_NeutralHadEt)
stream.select("recoGenMET_genMetCalo.NeutralHadEtFraction", GenMET_NeutralHadEtFraction)
stream.select("recoGenMET_genMetCalo.auxiliaryEnergy", GenMET_auxiliaryEnergy)
stream.select("recoGenMET_genMetCalo.charge", GenMET_charge)
stream.select("recoGenMET_genMetCalo.e_longitudinal", GenMET_e_longitudinal)
stream.select("recoGenMET_genMetCalo.emEnergy", GenMET_emEnergy)
stream.select("recoGenMET_genMetCalo.energy", GenMET_energy)
stream.select("recoGenMET_genMetCalo.et", GenMET_et)
stream.select("recoGenMET_genMetCalo.eta", GenMET_eta)
stream.select("recoGenMET_genMetCalo.hadEnergy", GenMET_hadEnergy)
stream.select("recoGenMET_genMetCalo.hasMasterClone", GenMET_hasMasterClone)
stream.select("recoGenMET_genMetCalo.hasMasterClonePtr", GenMET_hasMasterClonePtr)
stream.select("recoGenMET_genMetCalo.invisibleEnergy", GenMET_invisibleEnergy)
stream.select("recoGenMET_genMetCalo.isCaloMuon", GenMET_isCaloMuon)
stream.select("recoGenMET_genMetCalo.isConvertedPhoton", GenMET_isConvertedPhoton)
stream.select("recoGenMET_genMetCalo.isElectron", GenMET_isElectron)
stream.select("recoGenMET_genMetCalo.isGlobalMuon", GenMET_isGlobalMuon)
stream.select("recoGenMET_genMetCalo.isJet", GenMET_isJet)
stream.select("recoGenMET_genMetCalo.isMuon", GenMET_isMuon)
stream.select("recoGenMET_genMetCalo.isPhoton", GenMET_isPhoton)
stream.select("recoGenMET_genMetCalo.isStandAloneMuon", GenMET_isStandAloneMuon)
stream.select("recoGenMET_genMetCalo.isTrackerMuon", GenMET_isTrackerMuon)
stream.select("recoGenMET_genMetCalo.longLived", GenMET_longLived)
stream.select("recoGenMET_genMetCalo.mEtSig", GenMET_mEtSig)
stream.select("recoGenMET_genMetCalo.mass", GenMET_mass)
stream.select("recoGenMET_genMetCalo.massConstraint", GenMET_massConstraint)
stream.select("recoGenMET_genMetCalo.massSqr", GenMET_massSqr)
stream.select("recoGenMET_genMetCalo.mt", GenMET_mt)
stream.select("recoGenMET_genMetCalo.mtSqr", GenMET_mtSqr)
stream.select("recoGenMET_genMetCalo.numberOfDaughters", GenMET_numberOfDaughters)
stream.select("recoGenMET_genMetCalo.numberOfMothers", GenMET_numberOfMothers)
stream.select("recoGenMET_genMetCalo.numberOfSourceCandidatePtrs", GenMET_numberOfSourceCandidatePtrs)
stream.select("recoGenMET_genMetCalo.numberOfTracks", GenMET_numberOfTracks)
stream.select("recoGenMET_genMetCalo.p", GenMET_p)
stream.select("recoGenMET_genMetCalo.pdgId", GenMET_pdgId)
stream.select("recoGenMET_genMetCalo.phi", GenMET_phi)
stream.select("recoGenMET_genMetCalo.pt", GenMET_pt)
stream.select("recoGenMET_genMetCalo.px", GenMET_px)
stream.select("recoGenMET_genMetCalo.py", GenMET_py)
stream.select("recoGenMET_genMetCalo.pz", GenMET_pz)
stream.select("recoGenMET_genMetCalo.rapidity", GenMET_rapidity)
stream.select("recoGenMET_genMetCalo.significance", GenMET_significance)
stream.select("recoGenMET_genMetCalo.status", GenMET_status)
stream.select("recoGenMET_genMetCalo.sumEt", GenMET_sumEt)
stream.select("recoGenMET_genMetCalo.theta", GenMET_theta)
stream.select("recoGenMET_genMetCalo.threeCharge", GenMET_threeCharge)
stream.select("recoGenMET_genMetCalo.vertexChi2", GenMET_vertexChi2)
stream.select("recoGenMET_genMetCalo.vertexNdof", GenMET_vertexNdof)
stream.select("recoGenMET_genMetCalo.vertexNormalizedChi2", GenMET_vertexNormalizedChi2)
stream.select("recoGenMET_genMetCalo.vx", GenMET_vx)
stream.select("recoGenMET_genMetCalo.vy", GenMET_vy)
stream.select("recoGenMET_genMetCalo.vz", GenMET_vz)
stream.select("recoGenMET_genMetCalo.y", GenMET_y)
stream.select("recoGenParticle_genParticles.charge", GenParticle_charge)
stream.select("recoGenParticle_genParticles.collisionId", GenParticle_collisionId)
stream.select("recoGenParticle_genParticles.energy", GenParticle_energy)
stream.select("recoGenParticle_genParticles.et", GenParticle_et)
stream.select("recoGenParticle_genParticles.eta", GenParticle_eta)
stream.select("recoGenParticle_genParticles.hasMasterClone", GenParticle_hasMasterClone)
stream.select("recoGenParticle_genParticles.hasMasterClonePtr", GenParticle_hasMasterClonePtr)
stream.select("recoGenParticle_genParticles.isCaloMuon", GenParticle_isCaloMuon)
stream.select("recoGenParticle_genParticles.isConvertedPhoton", GenParticle_isConvertedPhoton)
stream.select("recoGenParticle_genParticles.isElectron", GenParticle_isElectron)
stream.select("recoGenParticle_genParticles.isGlobalMuon", GenParticle_isGlobalMuon)
stream.select("recoGenParticle_genParticles.isJet", GenParticle_isJet)
stream.select("recoGenParticle_genParticles.isMuon", GenParticle_isMuon)
stream.select("recoGenParticle_genParticles.isPhoton", GenParticle_isPhoton)
stream.select("recoGenParticle_genParticles.isStandAloneMuon", GenParticle_isStandAloneMuon)
stream.select("recoGenParticle_genParticles.isTrackerMuon", GenParticle_isTrackerMuon)
stream.select("recoGenParticle_genParticles.longLived", GenParticle_longLived)
stream.select("recoGenParticle_genParticles.mass", GenParticle_mass)
stream.select("recoGenParticle_genParticles.massConstraint", GenParticle_massConstraint)
stream.select("recoGenParticle_genParticles.massSqr", GenParticle_massSqr)
stream.select("recoGenParticle_genParticles.mt", GenParticle_mt)
stream.select("recoGenParticle_genParticles.mtSqr", GenParticle_mtSqr)
stream.select("recoGenParticle_genParticles.numberOfDaughters", GenParticle_numberOfDaughters)
stream.select("recoGenParticle_genParticles.numberOfMothers", GenParticle_numberOfMothers)
stream.select("recoGenParticle_genParticles.numberOfSourceCandidatePtrs", GenParticle_numberOfSourceCandidatePtrs)
stream.select("recoGenParticle_genParticles.p", GenParticle_p)
stream.select("recoGenParticle_genParticles.pdgId", GenParticle_pdgId)
stream.select("recoGenParticle_genParticles.phi", GenParticle_phi)
stream.select("recoGenParticle_genParticles.pt", GenParticle_pt)
stream.select("recoGenParticle_genParticles.px", GenParticle_px)
stream.select("recoGenParticle_genParticles.py", GenParticle_py)
stream.select("recoGenParticle_genParticles.pz", GenParticle_pz)
stream.select("recoGenParticle_genParticles.rapidity", GenParticle_rapidity)
stream.select("recoGenParticle_genParticles.status", GenParticle_status)
stream.select("recoGenParticle_genParticles.theta", GenParticle_theta)
stream.select("recoGenParticle_genParticles.threeCharge", GenParticle_threeCharge)
stream.select("recoGenParticle_genParticles.vertexChi2", GenParticle_vertexChi2)
stream.select("recoGenParticle_genParticles.vertexNdof", GenParticle_vertexNdof)
stream.select("recoGenParticle_genParticles.vertexNormalizedChi2", GenParticle_vertexNormalizedChi2)
stream.select("recoGenParticle_genParticles.vx", GenParticle_vx)
stream.select("recoGenParticle_genParticles.vy", GenParticle_vy)
stream.select("recoGenParticle_genParticles.vz", GenParticle_vz)
stream.select("recoGenParticle_genParticles.y", GenParticle_y)
stream.select("recoPFJet_ak5PFJets.HFEMEnergy", PFJet_HFEMEnergy)
stream.select("recoPFJet_ak5PFJets.HFEMEnergyFraction", PFJet_HFEMEnergyFraction)
stream.select("recoPFJet_ak5PFJets.HFEMMultiplicity", PFJet_HFEMMultiplicity)
stream.select("recoPFJet_ak5PFJets.HFHadronEnergy", PFJet_HFHadronEnergy)
stream.select("recoPFJet_ak5PFJets.HFHadronEnergyFraction", PFJet_HFHadronEnergyFraction)
stream.select("recoPFJet_ak5PFJets.HFHadronMultiplicity", PFJet_HFHadronMultiplicity)
stream.select("recoPFJet_ak5PFJets.charge", PFJet_charge)
stream.select("recoPFJet_ak5PFJets.chargedEmEnergy", PFJet_chargedEmEnergy)
stream.select("recoPFJet_ak5PFJets.chargedEmEnergyFraction", PFJet_chargedEmEnergyFraction)
stream.select("recoPFJet_ak5PFJets.chargedHadronEnergy", PFJet_chargedHadronEnergy)
stream.select("recoPFJet_ak5PFJets.chargedHadronEnergyFraction", PFJet_chargedHadronEnergyFraction)
stream.select("recoPFJet_ak5PFJets.chargedHadronMultiplicity", PFJet_chargedHadronMultiplicity)
stream.select("recoPFJet_ak5PFJets.chargedMuEnergy", PFJet_chargedMuEnergy)
stream.select("recoPFJet_ak5PFJets.chargedMuEnergyFraction", PFJet_chargedMuEnergyFraction)
stream.select("recoPFJet_ak5PFJets.chargedMultiplicity", PFJet_chargedMultiplicity)
stream.select("recoPFJet_ak5PFJets.constituentEtaPhiSpread", PFJet_constituentEtaPhiSpread)
stream.select("recoPFJet_ak5PFJets.constituentPtDistribution", PFJet_constituentPtDistribution)
stream.select("recoPFJet_ak5PFJets.electronEnergy", PFJet_electronEnergy)
stream.select("recoPFJet_ak5PFJets.electronEnergyFraction", PFJet_electronEnergyFraction)
stream.select("recoPFJet_ak5PFJets.electronMultiplicity", PFJet_electronMultiplicity)
stream.select("recoPFJet_ak5PFJets.energy", PFJet_energy)
stream.select("recoPFJet_ak5PFJets.et", PFJet_et)
stream.select("recoPFJet_ak5PFJets.eta", PFJet_eta)
stream.select("recoPFJet_ak5PFJets.etaetaMoment", PFJet_etaetaMoment)
stream.select("recoPFJet_ak5PFJets.etaphiMoment", PFJet_etaphiMoment)
stream.select("recoPFJet_ak5PFJets.hasMasterClone", PFJet_hasMasterClone)
stream.select("recoPFJet_ak5PFJets.hasMasterClonePtr", PFJet_hasMasterClonePtr)
stream.select("recoPFJet_ak5PFJets.isCaloMuon", PFJet_isCaloMuon)
stream.select("recoPFJet_ak5PFJets.isConvertedPhoton", PFJet_isConvertedPhoton)
stream.select("recoPFJet_ak5PFJets.isElectron", PFJet_isElectron)
stream.select("recoPFJet_ak5PFJets.isGlobalMuon", PFJet_isGlobalMuon)
stream.select("recoPFJet_ak5PFJets.isJet", PFJet_isJet)
stream.select("recoPFJet_ak5PFJets.isMuon", PFJet_isMuon)
stream.select("recoPFJet_ak5PFJets.isPhoton", PFJet_isPhoton)
stream.select("recoPFJet_ak5PFJets.isStandAloneMuon", PFJet_isStandAloneMuon)
stream.select("recoPFJet_ak5PFJets.isTrackerMuon", PFJet_isTrackerMuon)
stream.select("recoPFJet_ak5PFJets.jetArea", PFJet_jetArea)
stream.select("recoPFJet_ak5PFJets.longLived", PFJet_longLived)
stream.select("recoPFJet_ak5PFJets.mass", PFJet_mass)
stream.select("recoPFJet_ak5PFJets.massConstraint", PFJet_massConstraint)
stream.select("recoPFJet_ak5PFJets.massSqr", PFJet_massSqr)
stream.select("recoPFJet_ak5PFJets.maxDistance", PFJet_maxDistance)
stream.select("recoPFJet_ak5PFJets.mt", PFJet_mt)
stream.select("recoPFJet_ak5PFJets.mtSqr", PFJet_mtSqr)
stream.select("recoPFJet_ak5PFJets.muonEnergy", PFJet_muonEnergy)
stream.select("recoPFJet_ak5PFJets.muonEnergyFraction", PFJet_muonEnergyFraction)
stream.select("recoPFJet_ak5PFJets.muonMultiplicity", PFJet_muonMultiplicity)
stream.select("recoPFJet_ak5PFJets.nConstituents", PFJet_nConstituents)
stream.select("recoPFJet_ak5PFJets.nPasses", PFJet_nPasses)
stream.select("recoPFJet_ak5PFJets.neutralEmEnergy", PFJet_neutralEmEnergy)
stream.select("recoPFJet_ak5PFJets.neutralEmEnergyFraction", PFJet_neutralEmEnergyFraction)
stream.select("recoPFJet_ak5PFJets.neutralHadronEnergy", PFJet_neutralHadronEnergy)
stream.select("recoPFJet_ak5PFJets.neutralHadronEnergyFraction", PFJet_neutralHadronEnergyFraction)
stream.select("recoPFJet_ak5PFJets.neutralHadronMultiplicity", PFJet_neutralHadronMultiplicity)
stream.select("recoPFJet_ak5PFJets.neutralMultiplicity", PFJet_neutralMultiplicity)
stream.select("recoPFJet_ak5PFJets.numberOfDaughters", PFJet_numberOfDaughters)
stream.select("recoPFJet_ak5PFJets.numberOfMothers", PFJet_numberOfMothers)
stream.select("recoPFJet_ak5PFJets.numberOfSourceCandidatePtrs", PFJet_numberOfSourceCandidatePtrs)
stream.select("recoPFJet_ak5PFJets.p", PFJet_p)
stream.select("recoPFJet_ak5PFJets.pdgId", PFJet_pdgId)
stream.select("recoPFJet_ak5PFJets.phi", PFJet_phi)
stream.select("recoPFJet_ak5PFJets.phiphiMoment", PFJet_phiphiMoment)
stream.select("recoPFJet_ak5PFJets.photonEnergy", PFJet_photonEnergy)
stream.select("recoPFJet_ak5PFJets.photonEnergyFraction", PFJet_photonEnergyFraction)
stream.select("recoPFJet_ak5PFJets.photonMultiplicity", PFJet_photonMultiplicity)
stream.select("recoPFJet_ak5PFJets.pileup", PFJet_pileup)
stream.select("recoPFJet_ak5PFJets.pt", PFJet_pt)
stream.select("recoPFJet_ak5PFJets.px", PFJet_px)
stream.select("recoPFJet_ak5PFJets.py", PFJet_py)
stream.select("recoPFJet_ak5PFJets.pz", PFJet_pz)
stream.select("recoPFJet_ak5PFJets.rapidity", PFJet_rapidity)
stream.select("recoPFJet_ak5PFJets.status", PFJet_status)
stream.select("recoPFJet_ak5PFJets.theta", PFJet_theta)
stream.select("recoPFJet_ak5PFJets.threeCharge", PFJet_threeCharge)
stream.select("recoPFJet_ak5PFJets.vertexChi2", PFJet_vertexChi2)
stream.select("recoPFJet_ak5PFJets.vertexNdof", PFJet_vertexNdof)
stream.select("recoPFJet_ak5PFJets.vertexNormalizedChi2", PFJet_vertexNormalizedChi2)
stream.select("recoPFJet_ak5PFJets.vx", PFJet_vx)
stream.select("recoPFJet_ak5PFJets.vy", PFJet_vy)
stream.select("recoPFJet_ak5PFJets.vz", PFJet_vz)
stream.select("recoPFJet_ak5PFJets.y", PFJet_y)
stream.select("recoPFMET_pfMet.ChargedEMEt", PFMET_ChargedEMEt)
stream.select("recoPFMET_pfMet.ChargedEMEtFraction", PFMET_ChargedEMEtFraction)
stream.select("recoPFMET_pfMet.ChargedEMFraction", PFMET_ChargedEMFraction)
stream.select("recoPFMET_pfMet.ChargedHadEt", PFMET_ChargedHadEt)
stream.select("recoPFMET_pfMet.ChargedHadEtFraction", PFMET_ChargedHadEtFraction)
stream.select("recoPFMET_pfMet.ChargedHadFraction", PFMET_ChargedHadFraction)
stream.select("recoPFMET_pfMet.HFEMEt", PFMET_HFEMEt)
stream.select("recoPFMET_pfMet.HFEMEtFraction", PFMET_HFEMEtFraction)
stream.select("recoPFMET_pfMet.HFHadronEt", PFMET_HFHadronEt)
stream.select("recoPFMET_pfMet.HFHadronEtFraction", PFMET_HFHadronEtFraction)
stream.select("recoPFMET_pfMet.MuonEt", PFMET_MuonEt)
stream.select("recoPFMET_pfMet.MuonEtFraction", PFMET_MuonEtFraction)
stream.select("recoPFMET_pfMet.MuonFraction", PFMET_MuonFraction)
stream.select("recoPFMET_pfMet.NeutralEMEt", PFMET_NeutralEMEt)
stream.select("recoPFMET_pfMet.NeutralEMEtFraction", PFMET_NeutralEMEtFraction)
stream.select("recoPFMET_pfMet.NeutralEMFraction", PFMET_NeutralEMFraction)
stream.select("recoPFMET_pfMet.NeutralHadEt", PFMET_NeutralHadEt)
stream.select("recoPFMET_pfMet.NeutralHadEtFraction", PFMET_NeutralHadEtFraction)
stream.select("recoPFMET_pfMet.NeutralHadFraction", PFMET_NeutralHadFraction)
stream.select("recoPFMET_pfMet.Type6Et", PFMET_Type6Et)
stream.select("recoPFMET_pfMet.Type6EtFraction", PFMET_Type6EtFraction)
stream.select("recoPFMET_pfMet.Type7Et", PFMET_Type7Et)
stream.select("recoPFMET_pfMet.Type7EtFraction", PFMET_Type7EtFraction)
stream.select("recoPFMET_pfMet.charge", PFMET_charge)
stream.select("recoPFMET_pfMet.chargedHadronEt", PFMET_chargedHadronEt)
stream.select("recoPFMET_pfMet.chargedHadronEtFraction", PFMET_chargedHadronEtFraction)
stream.select("recoPFMET_pfMet.e_longitudinal", PFMET_e_longitudinal)
stream.select("recoPFMET_pfMet.electronEt", PFMET_electronEt)
stream.select("recoPFMET_pfMet.electronEtFraction", PFMET_electronEtFraction)
stream.select("recoPFMET_pfMet.energy", PFMET_energy)
stream.select("recoPFMET_pfMet.et", PFMET_et)
stream.select("recoPFMET_pfMet.eta", PFMET_eta)
stream.select("recoPFMET_pfMet.hasMasterClone", PFMET_hasMasterClone)
stream.select("recoPFMET_pfMet.hasMasterClonePtr", PFMET_hasMasterClonePtr)
stream.select("recoPFMET_pfMet.isCaloMuon", PFMET_isCaloMuon)
stream.select("recoPFMET_pfMet.isConvertedPhoton", PFMET_isConvertedPhoton)
stream.select("recoPFMET_pfMet.isElectron", PFMET_isElectron)
stream.select("recoPFMET_pfMet.isGlobalMuon", PFMET_isGlobalMuon)
stream.select("recoPFMET_pfMet.isJet", PFMET_isJet)
stream.select("recoPFMET_pfMet.isMuon", PFMET_isMuon)
stream.select("recoPFMET_pfMet.isPhoton", PFMET_isPhoton)
stream.select("recoPFMET_pfMet.isStandAloneMuon", PFMET_isStandAloneMuon)
stream.select("recoPFMET_pfMet.isTrackerMuon", PFMET_isTrackerMuon)
stream.select("recoPFMET_pfMet.longLived", PFMET_longLived)
stream.select("recoPFMET_pfMet.mEtSig", PFMET_mEtSig)
stream.select("recoPFMET_pfMet.mass", PFMET_mass)
stream.select("recoPFMET_pfMet.massConstraint", PFMET_massConstraint)
stream.select("recoPFMET_pfMet.massSqr", PFMET_massSqr)
stream.select("recoPFMET_pfMet.mt", PFMET_mt)
stream.select("recoPFMET_pfMet.mtSqr", PFMET_mtSqr)
stream.select("recoPFMET_pfMet.muonEt", PFMET_muonEt)
stream.select("recoPFMET_pfMet.muonEtFraction", PFMET_muonEtFraction)
stream.select("recoPFMET_pfMet.neutralHadronEt", PFMET_neutralHadronEt)
stream.select("recoPFMET_pfMet.neutralHadronEtFraction", PFMET_neutralHadronEtFraction)
stream.select("recoPFMET_pfMet.numberOfDaughters", PFMET_numberOfDaughters)
stream.select("recoPFMET_pfMet.numberOfMothers", PFMET_numberOfMothers)
stream.select("recoPFMET_pfMet.numberOfSourceCandidatePtrs", PFMET_numberOfSourceCandidatePtrs)
stream.select("recoPFMET_pfMet.numberOfTracks", PFMET_numberOfTracks)
stream.select("recoPFMET_pfMet.p", PFMET_p)
stream.select("recoPFMET_pfMet.pdgId", PFMET_pdgId)
stream.select("recoPFMET_pfMet.phi", PFMET_phi)
stream.select("recoPFMET_pfMet.photonEt", PFMET_photonEt)
stream.select("recoPFMET_pfMet.photonEtFraction", PFMET_photonEtFraction)
stream.select("recoPFMET_pfMet.pt", PFMET_pt)
stream.select("recoPFMET_pfMet.px", PFMET_px)
stream.select("recoPFMET_pfMet.py", PFMET_py)
stream.select("recoPFMET_pfMet.pz", PFMET_pz)
stream.select("recoPFMET_pfMet.rapidity", PFMET_rapidity)
stream.select("recoPFMET_pfMet.significance", PFMET_significance)
stream.select("recoPFMET_pfMet.status", PFMET_status)
stream.select("recoPFMET_pfMet.sumEt", PFMET_sumEt)
stream.select("recoPFMET_pfMet.theta", PFMET_theta)
stream.select("recoPFMET_pfMet.threeCharge", PFMET_threeCharge)
stream.select("recoPFMET_pfMet.vertexChi2", PFMET_vertexChi2)
stream.select("recoPFMET_pfMet.vertexNdof", PFMET_vertexNdof)
stream.select("recoPFMET_pfMet.vertexNormalizedChi2", PFMET_vertexNormalizedChi2)
stream.select("recoPFMET_pfMet.vx", PFMET_vx)
stream.select("recoPFMET_pfMet.vy", PFMET_vy)
stream.select("recoPFMET_pfMet.vz", PFMET_vz)
stream.select("recoPFMET_pfMet.y", PFMET_y)
stream.select("edmTriggerResults_TriggerResults.accept", TriggerResults_accept)
stream.select("edmTriggerResults_TriggerResults.error", TriggerResults_error)
stream.select("edmTriggerResults_TriggerResults.wasrun", TriggerResults_wasrun)
stream.select("nrecoGenJet_ak5GenJets", nGenJet)
stream.select("nrecoGenMET_genMetCalo", nGenMET)
stream.select("nrecoGenParticle_genParticles", nGenParticle)
stream.select("nrecoPFJet_ak5PFJets", nPFJet)
stream.select("nrecoPFMET_pfMet", nPFMET)
stream.select("edmTriggerResults_TriggerResults.size", nTriggerResults)

